name: 🐞 Bug
description: Fill a bug/issue
title: '🐞 [BUG] <title>'
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for taking the time to fill out this bug report! 🙂
        > We apologize for the inconvenience you are experiencing. To assist you effectively, kindly complete this form to the best of your ability. The more information you provide, the easier it will be for us to help you.

        **Helpfull Links 🔽**
        * [Code Of Conduct](https://www.github.com)
        * [Quick Start Guide](https://www.github.com)

  - type: textarea
    attributes:
      label: What happended? *
      description: Additionally, please let us know what you were expecting to happen.
      placeholder: Tell us what you see.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce *
      description: Could you kindly provide a clear and ordered set of steps to reproduce the issue, so that we can better understand and address the problem?
      placeholder: |
        1. Fill up the form.
        2. With this required value {name:'soft-node'}
        3. Click on submit button
        4. See the console => 404 not found
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior *
      description: A concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false

  - type: dropdown
    id: browsers
    attributes:
      label: What environment are you seeing the problem on?
      multiple: true
      options:
        - From Client Side
        - PostMan
        - CURL
