name: 🎁 Features
description: Fill a features/idea
title: '🎁 [FEATURES] <title>'
labels: [feature]
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for taking the time to fill out an idea for improving the project! 🥰
        > We welcome and appreciate all ideas you may have, and would greatly appreciate any level of detail you can provide to help us fully understand and consider them.

        **Helpfull Links 🔽**
        * [Code Of Conduct](https://www.github.com)
        * [Security Guide](https://www.github.com)

  - type: textarea
    attributes:
      label: Tell us about your idea *
      description: |
        - What changes do you envision?
        - Why do you believe the project needs to be modified?
        - What are the current use cases, and how do they support the project?
        - What do you hope to achieve as a result of these changes?"
      placeholder: Write your ideas..
    validations:
      required: true

  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
