name: 🙌 Help Wanted
description: Fill a help request
title: '🙌 [HELP] <title>'
labels: [help wanted]
body:
  - type: markdown
    attributes:
      value: |
        ## Please expline what help you want! 🥰

        **Helpfull Links 🔽**
        * [Code Of Conduct](https://www.github.com)
        * [Quick Guide](https://www.github.com)

  - type: textarea
    attributes:
      label: Tell us about your Problem *
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: true
